---
- name: Converge
  hosts: all
  tasks:
    - name: "Include geekoops-apache"
      include_role:
        name: "geekoops-apache"
    ## Setup test enviroment
    # Deploy a test site and serve it
    - name: Deploy test page (Debian)
      copy:
        content: |
          <html>Success! The test page is displayed correctly</html>
        dest: "{{www_dir}}/index.html"
        group: "{{ apache_group }}"
        owner: "{{ apache_user }}"
        mode: 0754
      register: deployed
      when: ansible_distribution == "Debian"
    - name: Deploy test page (openSUSE)
      copy:
        content: |
          <html>Success! The test page is displayed correctly</html>
        dest: "{{www_dir}}/htdocs/index.html"
        group: "{{ apache_group }}"
        owner: "{{ apache_user }}"
        mode: 0754
      register: deployed
      when: ansible_os_family == "Suse"
    - name: Perform apache check
      shell: "{{ apache_cmd }} -t"
      when: deployed.changed

    # Restart of apache is required for the new configuration
    - name: Restart apache
      systemd:
        name: "{{ apache_service }}"
        state: restarted
      when: deployed.changed
