---
- name: Converge
  hosts: all
  tasks:
    - name: "Include geekoops-apache"
      include_role:
        name: "geekoops-apache"
    ## Setup test enviroment
    # Deploy a test site and serve it
    - name: Deploy test page
      copy:
        content: |
          <html>Success! The test page is displayed correctly</html>
        dest: "{{www_dir}}/index.html"
        group: "{{ apache_group }}"
        owner: "{{ apache_user }}"
        mode: 0754
      register: deployed
    - name: Perform apache check
      shell: httpd -t
      when: deployed.changed

    # Restart of apache is required for the new configuration
    - name: Restart apache
      systemd:
        name: apache
        state: restarted
      when: deployed.changed
