---
- name: Converge
  hosts: all
  tasks:
    - name: "Include geekoops-apache"
      include_role:
        name: "geekoops-apache"
    ## Setup test enviroment
    # Deploy a test site and serve it
    - name: Deploy test page
      copy:
        content: |
          <html>Success! The test page is displayed correctly</html>
        dest: "{{www_dir}}/index.html"
        group: "{{ apache_user }}"
        owner: "{{ apache_group }}"
        mode: 0754
      register: deployed
    - name: Deploy apache configuration
      copy:
        content: |
              server {
                  listen 80 default_server;
                  listen [::]:80 default_server;
                  root {{ www_dir }};
                  index index.html index.htm;
                  location / {
                      try_files $uri $uri/ =404;
                  }
              }
        dest: "{{vhosts_dir}}/default.conf"
        owner: root
        group: root
        mode: 0644
      when: deployed.changed and deploy_apache_config == true

    - name: Perform apache check
      shell: httpd -t
      when: deployed.changed

    # Restart of apache is required for the new configuration
    - name: Restart apache
      systemd:
        name: apache
        state: restarted
      when: deployed.changed
